### ISSUE TITLE
Google search - local variable 'Google_Item_URL' referenced before assignment

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#10]
Hi, and thanks for your efforts in this project. 

Getting quite close, I can see that query data is getting populated in /Scrummage/lib/static/protected/output/google/2020/07/07
but no results on the GUI side. Having the following error in logs:

INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "POST /tasks/run/1 HTTP/1.1" 302 -
WARNING:root:2020-07-07 10:33:32 General Library - Using directory: /home/username_removed/Scrummage/lib/static/protected/output/google/2020/07/07.
INFO:root:2020-07-07 10:33:32 - Google_Search - Loading configuration data.
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /tasks HTTP/1.1" 200 -
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /static/js/main.js HTTP/1.1" 200 -
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /static/css/template.css HTTP/1.1" 200 -
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /static/js/jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /static/js/datatables.min.js HTTP/1.1" 200 -
INFO:werkzeug:10.10.220.100 - - [07/Jul/2020 10:33:32] "GET /static/images/sort_both.png HTTP/1.1" 200 -
INFO:root:2020-07-07 10:33:32 General Library - Main file created.
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
WARNING:root:2020-07-07 10:33:32 - Google_Search - local variable 'Google_Item_URL' referenced before assignment
INFO:root:2020-07-07 10:33:32 Connectors Library - Loading Scrummage's Main Database configuration data.

**Comment by matamorphosis** [comment]
Hey again,

My pleasure, glad you're finding it useful.

A little embarrassed made a dumb mistake just before committing. Should be fixed now, I tried three different searches that all worked perfectly. Hope this finally fixes it for you.
