### ISSUE TITLE
User right problems after installation

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#11]
Hi again.

There seems to be some user rights related problems after the installation. Few examples.

Data gets populated to /Scrummage/lib/static/protected/output/google/2020/07/07 only if you run Scrummage as a root.

And If you run Scrummage as standard user the folder 

/home/username_removed/Scrummage/lib/static/protected/output/google/

Cannot be created, nor the file 

/home/username_removed/Scrummage/lib/static/protected/output/google/google-log-file.log 

This can off course be fixed after install by manually creating the folder and file and giving the user rights to those, so can be considered low lever problem.

**Comment by matamorphosis** [comment]
Hey Joukahainen123,

Unfortunately, there's not much I can do about user rights. However here are a few things to consider:

1. Not sure which system you're using but I find using the latest Ubuntu distro works perfectly with this. I also find other Debian-based distributions such as Kali Linux works well with it too.
2. Ensure you clone Scrummage, and run it, from a directory the user you are using has read, write, and execute rights over.
3. When you install Scrummage, you should run the installer (dependencies.sh) as sudo as per the installation guide [here](https://github.com/matamorphosis/Scrummage/wiki/Installation)
```
user@linux:~$ sudo bash dependencies.sh
```

On lines 27-29 of this file you can see it creates the following directories.
```
mkdir ../lib/static/protected
mkdir ../lib/static/protected/output
mkdir ../lib/static/protected/screenshots
```
4. Ensure you run Scrummage as a regular user, as running it as sudo breaks certain functionality.
```
python3 Scrummage.py
```

Hope this helps.

**Comment by Joukahainen123** [comment]
Ok, thanks. Running in Ubuntu 20.04. Running the installation from user home directory and following the installation instructions literally. My main concern was that after installation /lib/static/protected has owner of root:root causing the running of Scrummage with user rights to fail.

this can off course be corercted after the install by running:

sudo chown -R standardusername:standardusername ../lib/static/protected

So not much of an trouble.

I have now the setup running fully, so thanks a lot.
