### ISSUE TITLE
NameError: name 'pro' is not defined emails

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#13]
Hi

I did activate email output. Having local postfix installation that will forward emails to the actual server.
For some reason I am getting a lot of emails like the one below to my local systems user ( [USERNAMEREMOVED] in the logs).

From [USERNAMEREMOVED]@scrummage.[DOMAINREMOVED]  Wed Jul  8 04:30:01 2020
Return-Path: <[USERNAMEREMOVED]@scrummage.[DOMAINREMOVED]>
X-Original-To: [USERNAMEREMOVED]
Delivered-To: [USERNAMEREMOVED]@scrummage.[DOMAINREMOVED]
Received: by scrummage.[DOMAINREMOVED] (Postfix, from userid 1000)
        id C11E922108D; Wed,  8 Jul 2020 04:30:01 +0000 (UTC)
From: root@scrummage.[DOMAINREMOVED] (Cron Daemon)
To: [USERNAMEREMOVED]@scrummage.[DOMAINREMOVED]
Subject: Cron <[USERNAMEREMOVED]@scrummage> /usr/bin/python3 /home/[USERNAMEREMOVED]/Scrummage/lib/plugin_caller.py -t 7
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/[USERNAMEREMOVED]>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=[USERNAMEREMOVED]>
Message-Id: <20200708043001.C11E922108D@scrummage.[DOMAINREMOVED]>
Date: Wed,  8 Jul 2020 04:30:01 +0000 (UTC)

Traceback (most recent call last):
  File "/home/[USERNAMEREMOVED]/Scrummage/lib/plugin_caller.py", line 365, in <module>
    Arguments = Parser.parse_args()/pro
NameError: name 'pro' is not defined

**Comment by matamorphosis** [comment]
Hi,

Not entirely sure what you mean by this, I just ran a search with my email address settings in place and it worked perfectly. For each result, an email will be sent. So yes there can be a lot of emails sent out.

Based on what you've sent I presume this is the result of a scheduled cronjob within the tool?

**Comment by Joukahainen123** [comment]
Ok, I have to double check my setup.  What did puzzle me in these, is that the email body (message) basically is an error.

"Traceback (most recent call last):
File "/home/[USERNAMEREMOVED]/Scrummage/lib/plugin_caller.py", line 365, in
Arguments = Parser.parse_args()/pro
NameError: name 'pro' is not defined"

**Comment by matamorphosis** [comment]
Very strange that it appeared in the email body. Turns out the "/pro" was some random text that ended up in the file. I've removed it, and the plugin_caller.py file should work for you now.

**Comment by Joukahainen123** [comment]
This fixed it. I did also change to use gmail account directly (so for generic information to anyone interested)  smtp.gmail.com:587 (tls) works fine.

**Comment by Joukahainen123** [comment]
Closing as fixed.
