### ISSUE TITLE
Error starting Scrummage

### ISSUE THREAD

**Issue by ottoscav** [matamorphosis/Scrummage#15]
ubuntu@ubuntu:~/Scrummage/lib$ python3 Scrummage.py 
Traceback (most recent call last):
  File "Scrummage.py", line 20, in <module>
    import os, re, plugin_caller, getpass, time, sys, threading, html, secrets, jwt, plugins.common.Connectors as Connectors, plugins.common.General as General, logging
  File "/home/ubuntu/Scrummage/lib/plugin_caller.py", line 1, in <module>
    import threading, plugins.common.Connectors as Connectors, plugins.common.General as General
  File "/home/ubuntu/Scrummage/lib/plugins/common/General.py", line 4, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Scrummage.py", line 3858, in <module>
    sys.exit(str(e))
NameError: name 'sys' is not defined

**Comment by matamorphosis** [comment]
Have you followed the installation guide?

**Comment by ottoscav** [comment]
Yes, exactly on Ubuntu 18.04.

**Comment by matamorphosis** [comment]
Okay sure, if you're sure it was successful. You can try the following:

I can see in the error python3 can't locate the packages bs4 and sys. These aren't included in the installation as there is an assumption these packages come installed when you install python3. That being said, try running the following commands to get yourself out of trouble:

```user@linux:~$ pip3 install bs4```
```user@linux:~$ pip3 install sys```

**Comment by ottoscav** [comment]
This worked, except I had to do pip3 install os-sys instead of sys. Thanks.
