### ISSUE TITLE
Error starting scrummage

### ISSUE THREAD

**Issue by jnanesh-byte** [matamorphosis/Scrummage#16]
Hi, 
Im trying to install scrummage on ubuntu 18.04. While starting scrummage, getting the following error.

root@spiderfoot-1:~/Scrummage/lib# python3 Scrummage.py 
'NoneType' object is not subscriptable
 Please assist. TIA

**Comment by matamorphosis** [comment]
Hi have you followed the installation instructions in the Wiki?

**Comment by matamorphosis** [comment]
https://github.com/matamorphosis/Scrummage/wiki/Installation

**Comment by matamorphosis** [comment]
Hi I release this is a year late, but setting up Scrummage is easier than ever now with docker.
https://github.com/matamorphosis/Scrummage/wiki/Installation-using-Docker
