### ISSUE TITLE
NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by meetgyn** [matamorphosis/Scrummage#2]
# python3 main.py
WARNING:root:2019-09-01 16:23:58 Failed to load configuration file.
WARNING:root:2019-09-01 16:23:58 Failed to connect to database.
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    Cursor = Connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
root@kronlab:/opt/ferramentas/Scrummage/lib#

**Comment by matamorphosis** [comment]
Have you added the correct database details to the config.json file?

**Comment by matamorphosis** [comment]
Installation script has been updated to now populate the database details to the config.json file. Also this error is now handled in the main.py file.

Will now close this issue.

**Comment by matamorphosis** [comment]
Noticed there was an issue with one of the commits, where some files were referring to "configuration/config.json" not "config/config.json", this might have been the issue you experienced.

Would recommend pulling the latest commit and re-run the install script.
