### ISSUE TITLE
[Feature Request] : Take screenshot automatically 

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#21]
Hi, and thanks for the great solution

This is not an actual issue, more like an feature request. Is it possible to get a screenshot taken automatically on all of the results?
This could be handy, because sometimes the pages I am looking for will die quite rapidly.

**Comment by matamorphosis** [comment]
Hi no worries,

I'll investigate the feasibility of this. By adding this I would probably add an option where you could choose to enable this functionality in the configuration file. The reason I haven't already included this is that the screenshots take on average about 3-5 seconds to be created so to get one for each result would slow down plugin runtime. But thanks for your interest I'll get back to you with my decision within the next few weeks.

**Comment by matamorphosis** [comment]
I've decided to include this change in version 3.2 alongside some bug fixes. Please pull the latest changes. You can find out how to set this option [here](https://github.com/matamorphosis/Scrummage/wiki/Evidencing-Results-through-Web-Scraping-and-Screenshots).

Thanks again for your recommendation.

**Comment by Joukahainen123** [comment]
Thanks. Closing.
