### ISSUE TITLE
name 'Chrome_Config' is not defined

### ISSUE THREAD

**Issue by BidoBi** [matamorphosis/Scrummage#22]
Hello, noob here

I have the following error after installing:

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
WARNING:root:2021-03-21 10:55:32 General Library - Message: session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 89.0.4389.90 with binary path /usr/bin/google-chrome
.
name 'Chrome_Config' is not defined

How do I fix this?

**Comment by BidoBi** [comment]
now I'm having this error

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
WARNING:root:2021-03-21 11:11:39 Connectors Library - Failed to connect to database.
CRITICAL:Scrummage:2021-03-21 11:11:39 Failed to load main database, please make sure the database details are added correctly to the configuration, and the PostgreSQL service is running.

**Comment by matamorphosis** [comment]
Hi BidoBi,

The chrome config issue is quite a pain, in that we've done what we can to save you the hassle of dealing with it but sometimes it still shows up. I'm going to address your issues in the order I see them.

1. In the first line you have an error `/usr/lib/python3/dist-packages/requests/init.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!`. You may need to use google to help you fix this, you can always verify it's installed with:
`pip3 install requests`
and verify it's up-to-date with:
`pip3 install --upgrade requests`
***Note:** Failure to fix this will cause issues when running almost all plugins.*

2. Regarding your chrome driver issue, it would appear you need to upgrade Google Chrome from a first glance. If you still experience this issue after upgrading chrome, please check out our debugging guide at https://github.com/matamorphosis/Scrummage/wiki/Screenshot-Troubleshooting

3. Lastly, assuming your installation was successful, you just need to start the PostgreSQL service. If you are on Debian/Ubuntu this can be achieved with the command `sudo service postgresql start`

Cheers,

matamorphosis

**Comment by BidoBi** [comment]
Thank you! I'll give this a go!
