### ISSUE TITLE
No module named 'flask_wtf'

### ISSUE THREAD

**Issue by DocKali** [matamorphosis/Scrummage#23]
Hi there,

I try to install Scrummage in Docker, download is fine, no error during install but when I try to run the tool I have the message "No module named 'flask_wtf'" and it exited. 
Where did this come from ? How can I solve that ?

Thanks for your help.

**Comment by matamorphosis** [comment]
Hi @DocKali,

Thanks for raising this, this is due the recent addition of the flask_wtf library to enhance aspects of the platform's security. The dependency list used by the installation had not been updated to reflect the change. This issue has now been rectified and can be resolved by deleting the docker image you pulled and pulling the image again with the `:latest` tag.

```console
docker pull ghcr.io/matamorphosis/scrummage:latest
docker run -p 5000:5000 ghcr.io/matamorphosis/scrummage:latest
```

**Comment by DocKali** [comment]
Excellent, thanks for your quick and useful answer. When pulling again the image with :latest tag, everything went fine, no more bug.

Thanks for your help !
