### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT when trying to connect to Web application

### ISSUE THREAD

**Issue by DocKali** [matamorphosis/Scrummage#25]
Hi there,

I run Scrummage in docker. No problem when I run the tool, no error messages. But when I try to connect to Web application, I have a ERR_CONNECTION_TIMED_OUT. 
I checked the firewall, everything seems OK, I test with Chrome, Firefox and Edge, always the same result.
I checked the IP with docker inspect, IP given by the tool is the good one.

Where does the error come from, any idea ?

Thanks for your help !

**Comment by matamorphosis** [comment]
Hi,

Firstly, you need to understand that there are two IP addresses at hand, with the docker image there is an assumption that this is understood. Docker images work similarly to Virtual Machine with a NAT set. Therefore, there is an internal IP address which Scrummage binds to but this cannot be accessed from your host. All docker images translate to a single IP address accessible by your host.

Assuming you're running Linux as the host, type `ifconfig` or `ip addr` in the CLI of you host, which should show you the appropriate IP address
![Check-Docker-IP-Address](https://user-images.githubusercontent.com/26025152/134753215-96f4a955-3cbf-4373-a3a2-941414b180b8.png)

Once you have that IP address, Scrummage can be accessed from any browser at https://\<YOUR-IP-ADDRESS\>:5000/

**Comment by matamorphosis** [comment]
Also just double checking when you run the docker image, you're exposing the port, like so:
`docker run -p 5000:5000 ghcr.io/matamorphosis/scrummage:latest`
