### ISSUE TITLE
Google Search

### ISSUE THREAD

**Issue by h0bit1** [matamorphosis/Scrummage#37]
No results for any keyword I use.

API and cx provided.

Is there any known issues or possible reasons why it's not working?

Thank you

**Comment by matamorphosis** [comment]
Hi @h0bit1,

There was a slight issue with the regex pattern used by the Google Search plugin, which has been fixed just now; however, what you are saying is not a bug. There are 4 fields that need to be filled out for this plugin, shown below.

Please ensure your API and CX are up-to-date and working, and ensure you provide the application name and version, which you would have picked during setup.

![Configure_Google](https://user-images.githubusercontent.com/26025152/140670968-aa8748a8-fdb0-4ccd-8c05-4f4c086e438a.png)

Additionally, this was already flagged in the discussion section, please defer to it for help on configuring plugins. If you find ambiguous errors after configuring and running, that is a good time to consider raising an issue.

[Relevant Discussion Forum Here](https://github.com/matamorphosis/Scrummage/discussions/35)

Thanks,

matamorphosis
