### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by balagpy** [matamorphosis/Scrummage#4]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from flask import Flask, render_template, json, flash, request, redirect, url_for, session, send_from_directory

**Comment by matamorphosis** [comment]
Please provide more details on this issue as this traceback doesn't provide enough details. Also ensure you're running the program with "python3 main.py".

**Comment by matamorphosis** [comment]
Going to close this issue as not enough information has been provided. I have tested and confirmed the latest commit works. Please ensure you follow the installation guide as per the [Wiki](https://github.com/matamorphosis/Scrummage/wiki), and follow guidelines to avoid such issues.
