### ISSUE TITLE
Creating Google Search task fails in 3.6

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#42]
For example creating Shodan searches works fine, but when I try to create Google Search I will get:

[2021-12-11 15:32:34,655] ERROR in Scrummage: list.remove(x): x not in list
ERROR:Scrummage:list.remove(x): x not in list
INFO:werkzeug:IPremoved - - [11/Dec/2021 15:32:34] "POST /tasks/new HTTP/1.1" 302 -
INFO:werkzeug:IPremoved - - [11/Dec/2021 15:32:34] "GET /tasks HTTP/1.1" 200 -
INFO:werkzeug:IPremoved - - [11/Dec/2021 15:32:34] "GET /static/css/template.css HTTP/1.1" 200 -

And the task is never created.

**Comment by matamorphosis** [comment]
HI @Joukahainen123, thanks for raising this bug. A simple oversight due to a recent change for the Google Search plugin to permit certain special characters for Google Dorking was causing the issue. This has since been resolved.
