### ISSUE TITLE
Installing script using deleted files

### ISSUE THREAD

**Issue by KeleranV** [matamorphosis/Scrummage#53]
Hello,
I'm currently trying to install the project on an Ubuntu 20.04 fresh install, and was encountering some issues.
In the `install.sh` script, when installing poetry and installing the project dependencies, the script use the `pyhon_requirements.txt` file, but it was deleted in a previous commit.

**Comment by matamorphosis** [comment]
I see you raised a pull request, which I've now merged to master, I assume that fixed the issue?

**Comment by KeleranV** [comment]
Hello,
Sorry I'm new to the process of forking to contribute, I thought that the master branch on the fork was mine, but it sent the code on your repo . It seems to work on my dev environment, but it might be because of other things I did.
I'll continue to test and code to ensure that the script work.
Sorry for the inconvenience

**Comment by matamorphosis** [comment]
No problem, I reviewed the change, and it addressed a gap in the last release. These days the docker image tends to take preference, and the manual install script, unfortunately gets neglected sometimes, so your effort is much appreciated!
