### ISSUE TITLE
Wiki Docker installation Option - 3 incorrect

### ISSUE THREAD

**Issue by animation101** [matamorphosis/Scrummage#57]
The [wiki page](https://github.com/matamorphosis/Scrummage/wiki/Installation-using-Docker#option-3-using-the-dockerfile-included-in-this-repository) states that the user should be in the install folder, the correct Dockerfile path is the [project root folder](https://github.com/matamorphosis/Scrummage/blob/main/Dockerfile)

The 3rd option should really be to modify that file with the correct time zone and other options then run a docker build.

**Comment by matamorphosis** [comment]
Thanks @animation101 

A recent change removed the Dockerfile from that path due to it being annoying to maintain as a duplicate to the Dockerfile in the root directory. Have updated the WIki accordingly.
