### ISSUE TITLE
Missing module 'xmltodict'

### ISSUE THREAD

**Issue by animation101** [matamorphosis/Scrummage#59]
Module xmltodict is missing from the venv from the Yandex plugin

error in logs:
Plugin Verifier - No module named 'xmltodict'.

Proposed solution:
`pip3 install --target=/Scrummage/.venv/lib/python3.9/site-packages xmltodict --upgrade`

**Comment by matamorphosis** [comment]
Thanks @animation101,

I have added the missing package; however, as the platform uses Poetry to manage packages, I had to use a different solution: `poetry add xmltodict`, which you should also follow if experimenting on a local instance.
