### ISSUE TITLE
Install script and adding user fails with Cursor' is not defined

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#6]
Hi
Running sudo bash dependencies.sh in latest Ubuntu server 18.04.4
It fails with following error:

Table created successfully in PostgreSQL 
PostgreSQL connection closed.
[+] Scrummage tables created.
Traceback (most recent call last):
  File "Create_User.py", line 78, in <module>
    Cursor.execute(PSQL_Select_Query, (username,))
NameError: name 'Cursor' is not defined
[+] Admin user created, user details:
Username: admin

And the admin user is not created. Getting similar "cursor not defined" error when trying to run Create_User.py also.

**Comment by matamorphosis** [comment]
Hi @Joukahainen123 thank you for your interest in Scrummage and raising this issue. It appears to have been a bug released with version 2.2. The Cursor object shouldn't have been capitalised and this issue has now been corrected. Please update your Create_User.py file and re-run it. Hopefully this should resolve your issue.

**Comment by Joukahainen123** [comment]
Thanks. Now working.
