### ISSUE TITLE
Craigslist Plugin broken

### ISSUE THREAD

**Issue by animation101** [matamorphosis/Scrummage#60]
https://github.com/matamorphosis/Scrummage/blob/c83fcf94a7c59db05b4933f0934458615ed05087/app/plugins/Craigslist_Search.py#L42

The RSS function in Craigslist has been deprecated causing this plugin to no longer function.

**Comment by matamorphosis** [comment]
Thanks for letting me know @animation101.

I have decommissioned this plugin in a recent change, until such a time I can find a new working solution.
