### ISSUE TITLE
Something wrong with the installer database creation.

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#7]
Gives the following errors:

[+] Database setup complete.
  File "Create_Tables.py", line 8
    DB_Info = Configuration_Data['postgresql']:
                                              ^
SyntaxError: invalid syntax
[+] Scrummage tables created.
  File "Create_User.py", line 24
    DB_Info = Configuration_Data['postgresql']:
                                              ^
SyntaxError: invalid syntax

**Comment by matamorphosis** [comment]
Hi Joukahainen123,

Thank you for raising this, the issue was a simple oversight in both these installation scripts in the latest release (2.4). Please pull the latest changes or re-download the latest release and re-run the dependencies.sh script.

Cheers,

matamorphosis
