### ISSUE TITLE
API key not valid with Google search using valid api key

### ISSUE THREAD

**Issue by Joukahainen123** [matamorphosis/Scrummage#9]
Hi for some reason the Google search is not functioning. I am quite sure that the settings in configuration are right (copy-pasted from working setup of Scumblr). What could be the issue here? Logs below.

INFO:werkzeug:10.10.220.100 - - [06/Jul/2020 15:07:38] "GET /static/images/sort_both.png HTTP/1.1" 200 -
WARNING:root:2020-07-06 15:07:38 - Google_Search - <HttpError 400 when requesting https://customsearch.googleapis.com/$discovery/rest?version=thescumblr&key=1.0 returned "API key not valid. Please pass a valid API key.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console', 'url': 'https://console.developers.google.com'}]}]">
INFO:root:2020-07-06 15:07:38 Connectors Library - Loading Scrummage's Main Database configuration data.
INFO:werkzeug:10.10.220.100 - - [06/Jul/2020 15:07:39] "GET /static/images/sort_asc.png HTTP/1.1" 200 -

**Comment by matamorphosis** [comment]
Hey Joukahainen123,

I appreciate your persistence. This was the result of a simple oversight from the latest change with the loading of configuration details. I've updated and retested the plugin from my end and seems fine now.

Just ensure your API details are set correctly in the config file.

    "google": {
        "cx": "CX GOES HERE",
        "application_name": "thescumblr",
        "application_version": "1.0",
        "developer_key": "KEY GOES HERE"
    },
